# Copyright 2019 Yoshiya Hinosawa. All rights reserved. Blue Oak license.
name: test
on:
  push:
    branches: [master]
jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check license lines
      uses: ./
