name: Check License Lines
on:
  push:
    branches: [master]
jobs:
  check-license-lines:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: License Checker
      uses: ddevassy/license_checker@master
