name: "Cache release dependency metadata"
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm install --production
    - uses: jonabc/setup-licensed@v1
      with:
        version: '2.x'
    - uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        config_file: .licensed.release.yml
        workflow: branch
